### ISSUE TITLE
Use normal GitHub releases?

### ISSUE THREAD

**Issue by therealpxc** [nix-community/nix-installers#46]
I've been using the pre-built RPMs here with a script, and found that the hashes changed for the same version (2.17.1) at the same URL, with no clear indication of why here in the commit logs. That was a bit unsettling.

Could this project have versioned releases and host the pre-built binaries there, maybe with some kind of version suffix or something?

**Comment by therealpxc** [comment]
Oops, this is a dupe of https://github.com/nix-community/nix-installers/issues/6

**Comment by Malix-Labs** [comment]
Duplicate of #6
