### ISSUE TITLE
Difference with DeterminateSystems/nix-installer

### ISSUE THREAD

**Issue by Malix-Labs** [nix-community/nix-installers#55]
Hello !

What's the difference between this project and https://github.com/DeterminateSystems/nix-installer ?

**Comment by adisbladis** [comment]
It's described in the readme https://github.com/nix-community/nix-installers?tab=readme-ov-file#nix-installers-for-legacy-imperative-distributions.

**Comment by Malix-Labs** [comment]
I read it already, but is the difference solely that this project is packaged while https://github.com/DeterminateSystems/nix-installer is not ?

What downside would there is to package https://github.com/DeterminateSystems/nix-installer instead ?

**Comment by adisbladis** [comment]
This is an installer as a distro-native package. 

With this repo:
You install a `.deb`/`.rpm`, and boom, you have Nix installed. You can also uninstall Nix using your distro-native package manager. Cleanup is handled by distro-native package manager.

With the experimental/detsys installers:
You have a program mutating files & impurely pulling stuff of the net, your distro-native package manager isn't aware of these files. Cleanup is handled by installer program.

I originally created this setup to be able to install Nix in corporate environments where impure installers are not permitted.

**Comment by Malix-Labs** [comment]
Okay !

I also published https://github.com/DeterminateSystems/nix-installer/issues/1225
