### ISSUE TITLE
use CCache to speed up Github Action builds ?

### ISSUE THREAD

**Issue by ZLangJIT** [nix-community/nix-installers#61]

**Comment by adisbladis** [comment]
We can't use ccache because of impurities but we can use the [nix-community binary cache](https://github.com/nix-community/nix-installers/commit/d1a9cacba2191bd86fc0b0ccebe0711c764444ee) (Cachix).

**Comment by ZLangJIT** [comment]
> We can't use ccache because of impurities but we can use the [nix-community binary cache](https://github.com/nix-community/nix-installers/commit/d1a9cacba2191bd86fc0b0ccebe0711c764444ee) (Cachix).

how would ccache introduce impurities ?
